config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'posts#index'
  resource :timeline, only: [:show]

  resources :posts do
    resources :comments
  end

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]

    member do
      get :following
      get :followers
    end
  end
  resource :profile, only: [:show, :update]

  namespace :api, default: {format: :json } do
    scope '/posts/:post_id' do
      resource :like, only: [:show, :create, :destroy]
    end
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
  validates :content, length: { maximum: 50 }, presence: true
  validates :user, presence: true

  belongs_to :user
  belongs_to :post

  after_create :send_email

  private
  def send_email
    mentioner = user
    mentioned_names = content.scan(/@(\w+)/).flatten
    mentioned_names.each do |name|
      mentionee = User.find_by(account_name: name)
      if mentionee.present?
        CommentMailer.new_comment(self, mentionee, user).deliver_later
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    @comment = Comment.new(user: current_user, post: @post)
    respond_to do |format|
      format.html
      format.json { render json: @comments }
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params.merge(user: current_user, post: @post))
    @comment.save!

    render json: @comment
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
        redirect_to post_comments_path(@post), notice: 'Updated successfully'
    else
      flash.now[:error] = 'Update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy!
    redirect_to post_comments_path(@post), status: :see_other, notice: 'Deleted successfully'
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/edit.html.haml
.container.form-container 
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @comment, url: post_comment_path(@post, @comment), method: 'put', local: true) do |f|
    .comment-nav 
      = link_to 'Cancel', post_comments_path(@post), class: 'cancel-btn'
      = f.submit 'Update', class: 'post-btn'   
    = f.text_field :content, class: 'comment-edit'
  .delete-section
    = button_to 'Delete', post_comment_path(@post, @comment), method: :delete, data: { confirm: 'Are you sure you want to delete this?'}, class: 'delete-btn'   

app/views/comments/index.html.haml
.container.comment-container#comment-index{data: { post_id: @post.id, current_user_id: current_user.id }}
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message
  .comment-nav
    =link_to image_tag('back-btn.png'), root_path, class: 'back-btn', data: { turbo: false }
    %p Comment
  .comments-container

  = form_with(model: @comment, url: post_comments_path(@comment.post), local: false) do |f|
    .textarea-wrapper{class: (@post.comments.size < 8 ? 'fixed-bottom' : nil)}
      .image-overlay
        = image_submit_tag("timeline/comment.png", class: "comment-submit-btn")
      .flex-grow
        = f.text_area :content, class: 'comment-submit'