config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'posts#index'
  resource :timeline, only: [:show]

  resources :posts do
    resources :comments
  end

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]

    member do
      get :following
      get :followers
    end
  end
  resource :profile, only: [:show, :update]

  namespace :api, default: {format: :json } do
    scope '/posts/:post_id' do
      resource :like, only: [:show, :create, :destroy]
    end
  end
end

app/views/commons/_posts.html.haml
.container.timeline-container
  .post-header
    = link_to new_post_path do
      = image_tag 'timeline/photo-camera.png', class: 'camera-icon'

    .dropdown
      = image_tag 'timeline/icon.png', class: 'human-icon'
      .dropdown-content 
        - if current_page?(root_path) 
          = link_to 'Timeline', timeline_path
        - else 
          = link_to 'NewPosts', root_path 
        = link_to 'Logout', destroy_user_session_path, data: { method: 'delete' } 
  - posts.each do |post|
    - path = post.user == current_user ? profile_path : account_path(post.user)
    .post_wrapper
      .post_imformation{id: "post_#{post.id}"}
        .icon
          - if post.user.profile&.avatar&.attached?
            = link_to path do
              = image_tag(post.user.profile.avatar)
          - else 
            =link_to path do
              =image_tag("avatar.svg")
        .post_detail
          %p.post-account_name= post.user.account_name
          %p.post_time= I18n.with_locale(:en) { time_ago_in_words(post.created_at) + ' ago' }

      - image_count = post.images.count

      - if image_count == 3
        .post_img.three-images
          .img_left_wrapper
            = image_tag url_for(post.images.first), class: 'img_left'
          .img_right_wrapper
            = image_tag url_for(post.images.second), class: 'img_right'
            = image_tag url_for(post.images.third), class: 'img_right'

      - elsif image_count == 2
        .post_img.two-images
          .img_two_wrapper
            = image_tag url_for(post.images.first), class: 'img_two'
            = image_tag url_for(post.images.second), class: 'img_two'

      - elsif image_count == 1
        .post_img.one-image
          = image_tag url_for(post.images.first), class: 'img_one'

      .post-actions{ data: { post_id: post.id } }
        - if user_signed_in?
          .like-button.hidden.active-heart-button 
            = image_tag 'timeline/active-like.png', class: 'heart-button' 
          .like-button.hidden.inactive-heart-button 
            = image_tag 'timeline/inactive-like.png', class: 'heart-button'
        .comment-button
          =link_to  post_comments_path(post) do
            = image_tag 'timeline/comment.png'
        - share_url = "https://twitter.com/share?url=#{ERB::Util.url_encode(root_url(anchor: "post_#{post.id}"))}&text=#{ERB::Util.url_encode(post.content)}"
        .share-button
          = link_to share_url, target: '_blank', rel:"noopener noreferrer", data: { turbo: false, toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do 
            = image_tag 'timeline/share.png'
      .post_content
        .like-message
          - if post.like_count == 0
            No likes yet
          - elsif post.like_count == 1
            = "#{post.likes.last.user.account_name} liked this post"
          -else
            = "#{post.likes.last.user.account_name} and #{post.like_count - 1} other liked this post"
        .post-footer 
          %p= post.user.account_name
          %p.post_content_detail= post.content

- unless Rails.env.test?
  = javascript_pack_tag 'post'

app/views/commons/_profile.html.haml
- user = defined?(@user) ? @user : current_user
- posts = local_assigns[:posts] || (user.posts.with_attached_images.order(created_at: :desc))

.container.profile_container
  .account_info{data: { user_id: user.id }}
    = link_to root_path, data: { turbo: false }  do
      = image_tag 'Tabs.svg', class: 'header_back'
    %p.account_name= user.account_name
    - unless user == current_user
      %button.unfollow-btn.hidden Unfollow
      %button.follow-btn.hidden Follow


  - if user == current_user
    = form_with( model: @profile, url: profile_path , method:'patch', local: false, id: 'profile-form', html: { multipart: true } ) do |f|
      = f.file_field :avatar, name: 'profile[avatar]', id:'avatar-input', style: 'display: none;'
      =image_tag user.profile&.avatar&.attached?? url_for(user.profile.avatar) : 'avatar.svg', id: 'avatar-upload', class: 'avatar_img' , style: 'cursor: pointer;'
  -else 
    =image_tag user.profile&.avatar&.attached?? url_for(user.profile.avatar) : 'avatar.svg', id: 'avatar-upload', class: 'avatar_img' , style: 'cursor: pointer;' 
  .stats-container
    .stat
      .stat-number= user.post_count
      .stat-label Posts
    .stat
      = link_to followers_account_path(user), class: 'follow-link' do
        .stat-number.stat-follower-number= user.follow_count
        .stat-label Followers
    .stat
      = link_to following_account_path(user), class: 'follow-link' do
        .stat-number= user.following_count
        .stat-label Following
        
  - posts.each do |post|
    - image_count = post.images.count
    - post_content = capture do
      - if image_count == 3
        .post_img.three-images
          .img_left_wrapper
            = image_tag url_for(post.images.first), class: 'img_left'
          .img_right_wrapper
            = image_tag url_for(post.images.second), class: 'img_right'
            = image_tag url_for(post.images.third), class: 'img_right'

      - elsif image_count == 2
        .post_img.two-images
          .img_two_wrapper
            = image_tag url_for(post.images.first), class: 'img_two'
            = image_tag url_for(post.images.second), class: 'img_two'

      - elsif image_count == 1
        .post_img.one-image
          = image_tag url_for(post.images.first), class: 'img_one' 

    - if user == current_user
      = link_to edit_post_path(post) do
        = post_content
    - else
      = post_content