config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'posts#index'
  resource :timeline, only: [:show]

  resources :posts do
    resources :comments
  end

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]

    member do
      get :following
      get :followers
    end
  end
  resource :profile, only: [:show, :update]

  namespace :api, default: {format: :json } do
    scope '/posts/:post_id' do
      resource :like, only: [:show, :create, :destroy]
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  validates :content, length: { maximum: 100 }, presence: true
  validate :validate_image_count, on: :create

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images

  scope :recent_24h, -> { where("posts.created_at >= ?", 24.hours.ago)}

  scope :with_like_count, -> {
    left_joins(:likes)
      .select("posts.*, COUNT(likes.id) as likes_count")
      .group("posts.id")
  }

  def like_count
    likes.count
  end

  def validate_image_count
    if images.blank?
      errors.add(:base, '画像を1枚以上アップロードしてください')
    elsif images.count > 3
      errors.add(:base, '画像は3枚までアップロードできます')
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: 'Successfully posted!'
    else
      flash.now[:error] = 'Failed to post'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    update_params = post_params.dup

    # images が存在していて、かつ中身が空文字 or 空配列なら削除
    if update_params[:images].present? && update_params[:images].all?(&:blank?)
      update_params.delete(:images)
    end

    if @post.update(update_params)
      redirect_to profile_path, notice: 'Updated successfully'
    else
      flash.now[:error] = 'Update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy!
    redirect_to profile_path, status: :see_other, notice: 'Deleted successfully'
  end

  private
  def post_params
    params.require(:post).permit(
      :content,
      images: []
    )
  end
end

app/views/posts/_form.html.haml
.container.form-container
  %ul
    - @post.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @post, local: true, multipart: true) do |f|
    .post-nav 
      - if @post.persisted?
        = link_to 'Cancel', profile_path, class: 'cancel-btn'
      - else
        = link_to 'Cancel', root_path, class: 'cancel-btn'
      %p Status 
      - if @post.persisted?
        = f.submit 'Update', class: 'post-btn'
      - else
        = f.submit 'Post', class: 'post-btn'

    .account-imformation
      .account_icon 
        = image_tag(current_user.profile&.avatar&.attached? ? url_for(current_user.profile.avatar) : 'avatar.svg', id: 'avatar-upload', class: 'avatar_img', style: 'cursor: pointer;')
      .account_post_name= current_user.account_name

    = f.text_field :content, class: 'post-content', placeholder: "What's on your mind ?"

    .file-upload-wrapper 
      = f.label :images, '+ Album', class: 'upload-label'
      = f.file_field :images, multiple: true, class: 'hidden-file-field', style: 'display: none;'

app/views/posts/edit.html.haml
= render 'form', post: @post

.delete-section
  = button_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to delete this?'}, class: 'delete-btn'

app/views/posts/index.html.haml
= render 'commons/posts', posts: @posts

app/views/posts/new.html.haml
= render 'form', post: @post